FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy backend files
COPY crm-integration-project/backend/main ./

# Expose port
EXPOSE 3000

# Start the application
CMD ["node", "app.js"]
